### ISSUE TITLE
phpspec is echoed rather than run

### ISSUE THREAD

**Issue by garhbod** [richardmiller/PhpSpecExtension#8]
After behat asks is you want to create a spec all I get is a dump of phpspec.

Using a windows machine if this applies. Doesn't matter if I specify the path of the .bat file or just phpspec itself it is just a dump of the file.

**Comment by garhbod** [comment]
Ok I have sorted that issue. The phpspec path needs to be the bin inside the phpspec folder. But I don't see the phpSpec questions until after I have guessed the answer.

Also now I'm having and issue with phpspec rerunner. It says Could not open input file: bin/phpspec even though my phpspec.yml specifies otherwise.

``` yml
# phpspec.yml
suites:
    main:
        namespace: App
        psr4_prefix: App
        src_path: app
        spec_path: tests
        rerunner:
            path: vendor/bin/phpspec
            commands: [describe, exemplify]
            config: phpspec.yml
extensions:
    - RMiller\BehatSpec\PhpSpecExtension
```
